context:
  name: sofa
  version: 24.12.99
  build_num: 0

recipe:
  name: ${{ name }}
  version: ${{ version }}

build:
  number: ${{ build_num }}
  string: nightly_${{ hash }}

cache:
  source:
    git: https://github.com/sofa-framework/sofa.git
    branch: master

    patches:
      # Some components that are part of the main SOFA code tree have to be compiled separately
      # as conda packages split the sofa-core part from GUI related components. SOFA CMakeFiles
      # needs to be patched to allow isolated compilation.
      - patches/0001-fix-missing-cmake-module-path-for-qglviewer-find-mod.patch

  build:
    script: scripts/build-cache

  requirements:
    build:
      - ${{ compiler('cxx') }}
      - ${{ stdlib('c') }}
      - cmake
      - if: unix
        then: make
      - if: win
        then: ninja
    host:
      - libboost-headers
      - zlib
      - tinyxml2
      - eigen
      - cxxopts
      - gtest

outputs:
  - package:
      name: libsofa
    build:
      script: scripts/install-core
      files:
        - ${{ "Library/" if win }}lib/${{ "lib" if not win }}Sofa*
        - ${{ "Library/" if win }}plugins/**/lib
        - if: win
          then:
            - Library/bin/*
            - Library/plugins/**/bin
        # for copying activation/deactivation scripts
        - etc/conda/*
    requirements:
      run:
        - zlib
      run_exports:
        - ${{ pin_subpackage('libsofa', upper_bound='x.x.x') }}
    tests:
      - package_contents:
          lib:
            - Sofa.Core*
    about:
      summary: Runtime librairies for the SOFA framework
      description: Runtime librairies for SOFA, a real-time multi-physics
       simulator with an emphasis on medical simulation and robotics.
      license: LGPL-2.1-or-later
      license_file:
        - LICENSE-LGPL.md
        - extlibs/difflib/LICENSE.MIT
        - extlibs/json/LICENSE.MIT
        - extlibs/stb/LICENSE.MIT

  - package:
      name: sofa-devel
    build:
      files:
        - ${{ "Library/" if win }}include/*
        - ${{ "Library/" if win }}lib/cmake/Sofa*
        - ${{ "Library/" if win }}plugins/**/include
        - ${{ "Library/" if win }}plugins/**/lib/cmake
    requirements:
      host:
        - ${{ pin_subpackage('libsofa', exact=True) }}
      run:
        - ${{ pin_subpackage('libsofa', exact=True) }}
      run_exports:
        - ${{ pin_subpackage('libsofa', upper_bound='x.x.x') }}
    tests:
      - package_contents:
          include:
            - Sofa.Core/sofa/core/init.h
          files:
            - ${{ "Library/" if win }}lib/cmake/Sofa.Core/Sofa.CoreConfig.cmake
            - ${{ "Library/" if win }}lib/cmake/Sofa.Core/Sofa.CoreConfigVersion.cmake
    about:
      summary: Development librairies for the SOFA framework
      description: Development librairies for SOFA, a real-time multi-physics
       simulator with an emphasis on medical simulation and robotics.
      license: LGPL-2.1-or-later
      license_file:
        - LICENSE-LGPL.md
        - extlibs/difflib/LICENSE.MIT
        - extlibs/json/LICENSE.MIT
        - extlibs/stb/LICENSE.MIT

  - package:
      name: sofa-gl
    build:
      script: scripts/build-sofa-gl
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - if: unix
          then: make
        - if: win 
          then: ninja
        - if: linux
          then: ${{ cdt('mesa-libgl-devel') }}
      host:
        - ${{ pin_subpackage('sofa-devel', exact=True) }}
        - glew
        - eigen
        - libboost-headers
        - if: linux
          then: libglu
      run:
        - ${{ pin_subpackage('libsofa', exact=True) }}
        - if: linux
          then: libglu
      run_exports:
        - ${{ pin_subpackage('sofa-gl', upper_bound='x.x.x') }}
    tests:
      - package_contents:
          include:
            - Sofa.GL/sofa/gl/initSofa.GL.h
          lib:
            - Sofa.GL*
          files:
            - ${{ "Library/" if win }}lib/cmake/Sofa.GL/Sofa.GLConfig.cmake
            - ${{ "Library/" if win }}lib/cmake/Sofa.GL/Sofa.GLConfigVersion.cmake
    about:
      summary: SOFA GL rendering library
      description: GL rendering library for SOFA, a real-time multi-physics
       simulator with an emphasis on medical simulation and robotics.
      license: LGPL-2.1-or-later
      license_file:
        - LICENSE-LGPL.md

  - package:
      name: sofa-gui-qt
    build:
      script: scripts/build-sofa-gui-qt
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - if: unix
          then: make
        - if: win
          then: ninja
        - if: linux
          then: ${{ cdt('mesa-libgl-devel') }}
      host:
        - ${{ pin_subpackage('sofa-devel', exact=True) }}
        - ${{ pin_subpackage('sofa-gl', exact=True) }}
        - qt-main
        - ffmpeg
        - libqglviewer
        - eigen
        - libboost-headers
        - cxxopts
      run:
        - ${{ pin_subpackage('libsofa', exact=True) }}
        - ${{ pin_subpackage('sofa-gl', exact=True) }}
        - glew
        - if: linux
          then: libglu
        # these are apparently required by qt on windows
        - if: win
          then:
            - libzlib
            - libjpeg-turbo
            - libpng
      run_exports:
        - ${{ pin_subpackage('sofa-gui-qt', upper_bound='x.x.x') }}
    tests:
      - package_contents:
          include:
            - Sofa.GUI.Qt/sofa/gui/qt/init.h
          lib:
            - Sofa.GUI.Qt*
          files:
            - ${{ "Library/" if win }}lib/cmake/Sofa.GUI.Qt/Sofa.GUI.QtConfig.cmake
            - ${{ "Library/" if win }}lib/cmake/Sofa.GUI.Qt/Sofa.GUI.QtConfigVersion.cmake
    about:
      summary: Qt-based GUI library for the SOFA framework
      description: Qt-based GUI library for SOFA, a real-time multi-physics
       simulator with an emphasis on medical simulation and robotics.
      license: GPL-2.0-or-later
      license_file:
        - Sofa/GUI/Qt/LICENSE.GPL.txt

  - package:
      name: sofa-app
    build:
      script: scripts/build-sofa-app
    requirements:
      build:
        - ${{ compiler('cxx') }}
        - ${{ stdlib('c') }}
        - cmake
        - if: unix
          then: make
        - if: win
          then: ninja
      host:
        - ${{ pin_subpackage('sofa-devel', exact=True) }}
        - ${{ pin_subpackage('sofa-gui-qt', exact=True) }}
        - eigen
        - libboost-headers
        - cxxopts
      run:
        - ${{ pin_subpackage('libsofa', exact=True) }}
        - ${{ pin_subpackage('sofa-gui-qt', exact=True) }}
    tests:
      - package_contents:
          bin:
            - runSofa
    about:
      summary: Applications and ressources for the SOFA framework
      description: Application (runSofa) and ressources (examples and share) for SOFA,
       a real-time multi-physics simulator with an emphasis on medical simulation and robotics.
      license: GPL-2.0-or-later
      license_file:
        - applications/projects/LICENSE.GPL.txt

extra:
  recipe-maintainers:
    - olivier-roussel
    - hugtalbot
