c_stdlib_version:
- '2.17'
c_stdlib:
- sysroot
cdt_name:
- cos7
c_compiler:
- gcc
cxx_compiler:
- gxx
cxx_compiler_version:
- '13'
docker_image:
- quay.io/condaforge/linux-anvil-x86_64:alma9
target_platform:
- linux-64