name: sofa
channels:
  - conda-forge
dependencies:
  - cmake
  - ninja
  - cxx-compiler
  - libboost-headers
  - zlib
  - tinyxml2
  - eigen
  - cxxopts
  - gtest
  - glew
  - qt-main
  - ffmpeg
  - libqglviewer
  - mesa-libgl-devel-cos7-x86_64
