name: osx-64

on: workflow_dispatch

jobs:
  build-publish-sofa:
    name: "Build and publish SOFA conda packages for ${{ matrix.os }}"
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        build_type: [Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sofa-conda-ci
        auto-update-conda: true
        miniforge-version: latest

    - name: Install conda environment
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci
        conda install anaconda-client rattler-build=0.31.1 -c conda-forge
        conda config --set anaconda_upload no

    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Build & publish sofa conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa/recipe.yaml --variant-config ../configs/osx64.yaml --output-dir $PKG_DIR --experimental
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/*sofa*.conda --force

    - name: Build & publish sofa-beamadapter conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-beamadapter/recipe.yaml --variant-config ../configs/osx64.yaml --output-dir $PKG_DIR --experimental
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-beamadapter*.conda --force

  build-publish-sofa-plugins-with-python:
    name: "Build and publish SOFA plugins conda packages for ${{ matrix.os }} on Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    needs: build-publish-sofa

    strategy:
      fail-fast: false
      matrix:
        os: [macos-13]
        build_type: [Release]
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sofa-conda-ci-py${{ matrix.python-version }}
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        miniforge-version: latest

    - name: Install conda environment
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        conda install anaconda-client rattler-build=0.31.1
        conda config --set anaconda_upload no

    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    - name: Build & publish sofa-python3 conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-python3/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-python3*.conda --force
        
    - name: Build & publish sofa-stlib conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-stlib/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-stlib*.conda --force

    - name: Build & publish sofa-modelorderreduction conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-modelorderreduction/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-modelorderreduction*.conda --force

    - name: Build & publish sofa-softrobots conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-softrobots/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-softrobots*.conda --force

    - name: Build & publish sofa-cosserat conda package
      shell: bash -l {0}
      run: |
        conda activate sofa-conda-ci-py${{ matrix.python-version }}
        cd conda/recipes
        PKG_DIR=../../../rattler-bld
        rattler-build build --recipe sofa-cosserat/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
        anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-cosserat*.conda --force

    # - name: Build & publish sofa-softrobotsinverse conda package
    #   shell: bash -l {0}
    #   run: |
    #     conda activate sofa-conda-ci-py${{ matrix.python-version }}
    #     cd conda/recipes
    #     PKG_DIR=../../../rattler-bld
    #     rattler-build build --recipe sofa-softrobotsinverse/recipe.yaml --variant-config ../configs/osx64.yaml --variant-config ../configs/python-${{ matrix.python-version }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c sofa-framework-prerelease
    #     anaconda -t ${{ secrets.ANACONDA_PRERELEASE_TOKEN }} upload -u sofa-framework-prerelease -l main $PKG_DIR/**/sofa-softrobotsinverse*.conda --force