name: common-build-publish-sofa-package

on:
  workflow_call:
    inputs:
      package-name:
        required: true
        type: string
      runner:
        required: true
        type: string
      platform:
        required: true
        type: string        
      python:
        required: false
        type: string
      recipe-dir:
        required: true
        type: string
      channel:
        required: true
        type: string
    secrets:
      api-key:
        required: true

jobs:
  build-publish-sofa:
    name: "Build and publish  ${{ inputs.package-name }} - ${{ inputs.platform }} (py${{ inputs.python }} ) conda packages on ${{ inputs.runner }}"
    runs-on: ${{ inputs.runner }}
    steps:
    # hotfix for linux arm64 runners that have a permission bug
    # https://github.com/orgs/community/discussions/148648#discussioncomment-11858098
    - name: Fix PATH and XDG_CONFIG_HOME for ARM64 Linux runners (actions/partner-runner-images#25)
      if: contains(inputs.runner, 'ubuntu') && contains(inputs.runner, 'arm')
      run: for var in PATH XDG_CONFIG_HOME; do sed -Ee "s/^/${var}=/" -e 's/(runner)admin/\1/g' <<< "${!var}"; done | tee -a "$GITHUB_ENV"

    - uses: actions/checkout@v4
      with:
        submodules: recursive

    # We force to use a conda env located close to filesystem root on Windows to bypass a compilation bug with SOFA
    # due to too long filename, even if LongPath registry key is enabled
    - name: Install miniconda [Windows]
      if: contains(inputs.runner, 'windows')
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: c:\so
        auto-update-conda: true
        miniforge-version: latest

    - name: Install miniconda [Linux x64 & macOS]
      if: contains(inputs.runner, 'windows') == false && !(contains(inputs.runner, 'ubuntu') && contains(inputs.runner, 'arm'))
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sofa-conda-ci
        auto-update-conda: true
        miniforge-version: latest

    - name: Install miniconda [Linux aarch64]
      if: contains(inputs.runner, 'ubuntu') && contains(inputs.runner, 'arm')
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: sofa-conda-ci
        auto-update-conda: true
        miniforge-version: latest
        architecture: aarch64

    - name: Install conda environment
      shell: bash -l {0}
      run: |
        conda install rattler-build -c conda-forge

    - name: Show conda config
      shell: bash -l {0}
      run: |
        conda info
        conda list
        conda config --show-sources
        conda config --show
        printenv | sort

    # Same remark here about too long filename bug on windows, we have to force the output directory accordingly on windows
    - name: Build & publish sofa conda package
      shell: bash -l {0}
      run: |
        conda info
        cd conda/recipes/${{ inputs.recipe-dir }}
        if [[ ${{ inputs.runner }} == "windows"* ]]; then
          PKG_DIR=c:/so/bld
        else
          PKG_DIR=../../../../rattler-bld
        fi
        if [ ! -z "${{ inputs.python }}" ]; then
          rattler-build build --recipe ${{ inputs.package-name }}/recipe.yaml --variant-config ../../configs/${{ inputs.platform }}.yaml --variant-config ../../configs/python-${{ inputs.python }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c https://prefix.dev/${{ inputs.channel }} --channel-priority disabled
        else
          rattler-build build --recipe ${{ inputs.package-name }}/recipe.yaml --variant-config ../../configs/${{ inputs.platform }}.yaml --output-dir $PKG_DIR --experimental -c conda-forge -c https://prefix.dev/${{ inputs.channel }} --channel-priority disabled
        fi
        for file in $PKG_DIR/**/*${{ inputs.package-name }}*.conda; do
          rattler-build upload prefix -c ${{ inputs.channel }} --api-key ${{ secrets.api-key }} "$file"
        done